/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#311400",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary-container": "#00285d",
        "error": "#ffb4ab",
        "surface-container": "#171f33",
        "tertiary-container": "#df7412",
        "outline-variant": "#424754",
        "surface-container-lowest": "#060e20",
        "primary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#c2c6d6",
        "background": "#0b1326",
        "on-secondary-fixed": "#0d1c2d",
        "primary": "#adc6ff",
        "surface": "#0b1326",
        "surface-container-low": "#131b2e",
        "on-secondary-container": "#a7b6cc",
        "surface-bright": "#31394d",
        "secondary-fixed": "#d4e4fa",
        "on-primary-fixed": "#001a42",
        "inverse-primary": "#005ac2",
        "secondary-container": "#39485a",
        "surface-container-highest": "#2d3449",
        "on-tertiary-container": "#461f00",
        "inverse-on-surface": "#283044",
        "on-secondary": "#233143",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#b9c8de",
        "on-background": "#dae2fd",
        "outline": "#8c909f",
        "inverse-surface": "#dae2fd",
        "secondary": "#b9c8de",
        "error-container": "#93000a",
        "on-primary": "#002e6a",
        "on-tertiary-fixed-variant": "#723600",
        "surface-dim": "#0b1326",
        "on-surface": "#dae2fd",
        "primary-container": "#4d8eff",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#690005",
        "surface-variant": "#2d3449",
        "on-secondary-fixed-variant": "#39485a",
        "surface-container-high": "#222a3d",
        "on-error-container": "#ffdad6",
        "surface-tint": "#adc6ff",
        "on-tertiary": "#502400",
        "on-primary-fixed-variant": "#004395",
        "tertiary": "#ffb786"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "unit": "4px",
        "sm": "8px",
        "margin-desktop": "32px",
        "xs": "4px",
        "xl": "40px",
        "gutter": "20px",
        "lg": "24px",
        "md": "16px",
        "container-max": "1440px",
        "sidebar-width": "240px"
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["13px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-code": ["13px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
